/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserActionsService } from "../userActions.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserActionsCreateInput } from "./UserActionsCreateInput";
import { UserActions } from "./UserActions";
import { UserActionsFindManyArgs } from "./UserActionsFindManyArgs";
import { UserActionsWhereUniqueInput } from "./UserActionsWhereUniqueInput";
import { UserActionsUpdateInput } from "./UserActionsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserActionsControllerBase {
  constructor(
    protected readonly service: UserActionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserActions })
  @nestAccessControl.UseRoles({
    resource: "UserActions",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserActions(
    @common.Body() data: UserActionsCreateInput
  ): Promise<UserActions> {
    return await this.service.createUserActions({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        fromUserId: true,
        toUserId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserActions] })
  @ApiNestedQuery(UserActionsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserActions",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userActionsItems(
    @common.Req() request: Request
  ): Promise<UserActions[]> {
    const args = plainToClass(UserActionsFindManyArgs, request.query);
    return this.service.userActionsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        fromUserId: true,
        toUserId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserActions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserActions",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userActions(
    @common.Param() params: UserActionsWhereUniqueInput
  ): Promise<UserActions | null> {
    const result = await this.service.userActions({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        fromUserId: true,
        toUserId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserActions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserActions",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserActions(
    @common.Param() params: UserActionsWhereUniqueInput,
    @common.Body() data: UserActionsUpdateInput
  ): Promise<UserActions | null> {
    try {
      return await this.service.updateUserActions({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          actionType: true,
          timestamp: true,

          user: {
            select: {
              id: true,
            },
          },

          fromUserId: true,
          toUserId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserActions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserActions",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserActions(
    @common.Param() params: UserActionsWhereUniqueInput
  ): Promise<UserActions | null> {
    try {
      return await this.service.deleteUserActions({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          actionType: true,
          timestamp: true,

          user: {
            select: {
              id: true,
            },
          },

          fromUserId: true,
          toUserId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
