/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserMatchesService } from "../userMatches.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserMatchesCreateInput } from "./UserMatchesCreateInput";
import { UserMatches } from "./UserMatches";
import { UserMatchesFindManyArgs } from "./UserMatchesFindManyArgs";
import { UserMatchesWhereUniqueInput } from "./UserMatchesWhereUniqueInput";
import { UserMatchesUpdateInput } from "./UserMatchesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserMatchesControllerBase {
  constructor(
    protected readonly service: UserMatchesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserMatches })
  @nestAccessControl.UseRoles({
    resource: "UserMatches",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserMatches(
    @common.Body() data: UserMatchesCreateInput
  ): Promise<UserMatches> {
    return await this.service.createUserMatches({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isMatch: true,
        matchDate: true,
        user1: true,
        user2: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserMatches] })
  @ApiNestedQuery(UserMatchesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserMatches",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userMatchesItems(
    @common.Req() request: Request
  ): Promise<UserMatches[]> {
    const args = plainToClass(UserMatchesFindManyArgs, request.query);
    return this.service.userMatchesItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isMatch: true,
        matchDate: true,
        user1: true,
        user2: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserMatches })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserMatches",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userMatches(
    @common.Param() params: UserMatchesWhereUniqueInput
  ): Promise<UserMatches | null> {
    const result = await this.service.userMatches({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isMatch: true,
        matchDate: true,
        user1: true,
        user2: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserMatches })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserMatches",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserMatches(
    @common.Param() params: UserMatchesWhereUniqueInput,
    @common.Body() data: UserMatchesUpdateInput
  ): Promise<UserMatches | null> {
    try {
      return await this.service.updateUserMatches({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isMatch: true,
          matchDate: true,
          user1: true,
          user2: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserMatches })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserMatches",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserMatches(
    @common.Param() params: UserMatchesWhereUniqueInput
  ): Promise<UserMatches | null> {
    try {
      return await this.service.deleteUserMatches({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isMatch: true,
          matchDate: true,
          user1: true,
          user2: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
