/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { PhotoFindManyArgs } from "../../photo/base/PhotoFindManyArgs";
import { Photo } from "../../photo/base/Photo";
import { PhotoWhereUniqueInput } from "../../photo/base/PhotoWhereUniqueInput";
import { PlacesFindManyArgs } from "../../places/base/PlacesFindManyArgs";
import { Places } from "../../places/base/Places";
import { PlacesWhereUniqueInput } from "../../places/base/PlacesWhereUniqueInput";
import { UserActionsFindManyArgs } from "../../userActions/base/UserActionsFindManyArgs";
import { UserActions } from "../../userActions/base/UserActions";
import { UserActionsWhereUniqueInput } from "../../userActions/base/UserActionsWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
        aboutMe: true,
        occupation: true,
        education: true,
        hometown: true,
        height: true,
        smokingStatus: true,
        children: true,
        profilePicture: true,
        phoneNumber: true,
        profileVerified: true,
        phoneNumberVerified: true,
        birthday: true,
        gender: true,
        showGender: true,
        longitude: true,
        latitude: true,
        interests: true,
        name: true,
        surname: true,
        aboutMatch: true,
        socialMode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
        aboutMe: true,
        occupation: true,
        education: true,
        hometown: true,
        height: true,
        smokingStatus: true,
        children: true,
        profilePicture: true,
        phoneNumber: true,
        profileVerified: true,
        phoneNumberVerified: true,
        birthday: true,
        gender: true,
        showGender: true,
        longitude: true,
        latitude: true,
        interests: true,
        name: true,
        surname: true,
        aboutMatch: true,
        socialMode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
        aboutMe: true,
        occupation: true,
        education: true,
        hometown: true,
        height: true,
        smokingStatus: true,
        children: true,
        profilePicture: true,
        phoneNumber: true,
        profileVerified: true,
        phoneNumberVerified: true,
        birthday: true,
        gender: true,
        showGender: true,
        longitude: true,
        latitude: true,
        interests: true,
        name: true,
        surname: true,
        aboutMatch: true,
        socialMode: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          username: true,
          email: true,
          roles: true,
          aboutMe: true,
          occupation: true,
          education: true,
          hometown: true,
          height: true,
          smokingStatus: true,
          children: true,
          profilePicture: true,
          phoneNumber: true,
          profileVerified: true,
          phoneNumberVerified: true,
          birthday: true,
          gender: true,
          showGender: true,
          longitude: true,
          latitude: true,
          interests: true,
          name: true,
          surname: true,
          aboutMatch: true,
          socialMode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          username: true,
          email: true,
          roles: true,
          aboutMe: true,
          occupation: true,
          education: true,
          hometown: true,
          height: true,
          smokingStatus: true,
          children: true,
          profilePicture: true,
          phoneNumber: true,
          profileVerified: true,
          phoneNumberVerified: true,
          birthday: true,
          gender: true,
          showGender: true,
          longitude: true,
          latitude: true,
          interests: true,
          name: true,
          surname: true,
          aboutMatch: true,
          socialMode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/photos")
  @ApiNestedQuery(PhotoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "read",
    possession: "any",
  })
  async findPhotos(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Photo[]> {
    const query = plainToClass(PhotoFindManyArgs, request.query);
    const results = await this.service.findPhotos(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        imageName: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/photos")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectPhotos(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      photos: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/photos")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updatePhotos(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      photos: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/photos")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectPhotos(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PhotoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      photos: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/place")
  @ApiNestedQuery(PlacesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Places",
    action: "read",
    possession: "any",
  })
  async findPlace(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Places[]> {
    const query = plainToClass(PlacesFindManyArgs, request.query);
    const results = await this.service.findPlace(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,
        createdBy: true,
        image: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/place")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectPlace(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PlacesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      place: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/place")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updatePlace(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PlacesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      place: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/place")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectPlace(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PlacesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      place: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/userActionsItems")
  @ApiNestedQuery(UserActionsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserActions",
    action: "read",
    possession: "any",
  })
  async findUserActionsItems(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserActions[]> {
    const query = plainToClass(UserActionsFindManyArgs, request.query);
    const results = await this.service.findUserActionsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        fromUserId: true,
        toUserId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userActionsItems")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectUserActionsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserActionsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userActionsItems: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userActionsItems")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateUserActionsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserActionsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userActionsItems: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userActionsItems")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectUserActionsItems(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserActionsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userActionsItems: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
