import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { PhotoListRelationFilter } from "../photo/PhotoListRelationFilter";
import { PlacesListRelationFilter } from "../places/PlacesListRelationFilter";
import { UserActionsListRelationFilter } from "../userActions/UserActionsListRelationFilter";

export type UserWhereInput = {
  id?: StringFilter;
  firstName?: StringNullableFilter;
  lastName?: StringNullableFilter;
  username?: StringFilter;
  email?: StringNullableFilter;
  aboutMe?: StringNullableFilter;
  occupation?: StringNullableFilter;
  education?: StringNullableFilter;
  hometown?: StringNullableFilter;
  height?: IntNullableFilter;
  smokingStatus?: BooleanNullableFilter;
  children?: BooleanNullableFilter;
  profilePicture?: StringNullableFilter;
  phoneNumber?: StringNullableFilter;
  profileVerified?: BooleanNullableFilter;
  phoneNumberVerified?: BooleanNullableFilter;
  birthday?: DateTimeNullableFilter;
  gender?: "Option1";
  showGender?: BooleanNullableFilter;
  longitude?: FloatNullableFilter;
  latitude?: FloatNullableFilter;
  name?: StringNullableFilter;
  surname?: StringNullableFilter;
  aboutMatch?: StringNullableFilter;
  socialMode?: BooleanNullableFilter;
  photos?: PhotoListRelationFilter;
  place?: PlacesListRelationFilter;
  userActionsItems?: UserActionsListRelationFilter;
};
