import { JsonValue } from "type-fest";
import { Photo } from "../photo/Photo";
import { Places } from "../places/Places";
import { UserActions } from "../userActions/UserActions";

export type User = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  firstName: string | null;
  lastName: string | null;
  username: string;
  email: string | null;
  roles: JsonValue;
  aboutMe: string | null;
  occupation: string | null;
  education: string | null;
  hometown: string | null;
  height: number | null;
  smokingStatus: boolean | null;
  children: boolean | null;
  profilePicture: string | null;
  phoneNumber: string | null;
  profileVerified: boolean | null;
  phoneNumberVerified: boolean | null;
  birthday: Date | null;
  gender?: "Option1" | null;
  showGender: boolean | null;
  longitude: number | null;
  latitude: number | null;
  interests?: Array<"Option1">;
  name: string | null;
  surname: string | null;
  aboutMatch: string | null;
  socialMode: boolean | null;
  photos?: Array<Photo>;
  place?: Array<Places>;
  userActionsItems?: Array<UserActions>;
};
